<?php

namespace AppBundle\Repository;

/**
 * InstallmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallmentRepository extends \Doctrine\ORM\EntityRepository
{

}
