<?php

namespace AppBundle\Repository;

/**
 * LoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLoansByAreaId($areaId)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 0')
            ->andWhere('l.area = :areaId')
            ->setParameter('areaId', $areaId)
            ->getQuery()
            ->getResult();
    }

    public function findLoansBySearch($areaId, $search)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 0')
            ->andWhere('l.area = :areaId')
            ->andWhere('l.loanCode LIKE :search')
            ->setParameter('areaId', $areaId)
            ->setParameter('search', '%' . $search . '%')
            ->getQuery()
            ->getResult();
    }

    public function findCompletedLoansByAreaId($areaId)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 1')
            ->andWhere('l.area = :areaId')
            ->setParameter('areaId', $areaId)
            ->getQuery()
            ->getResult();
    }

    public function findCompletedLoansBySearch($areaId, $search)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 1')
            ->andWhere('l.area = :areaId')
            ->andWhere('l.loanCode LIKE :search')
            ->setParameter('areaId', $areaId)
            ->setParameter('search', '%' . $search . '%')
            ->getQuery()
            ->getResult();
    }
}
