<?php

namespace AppBundle\Repository;

/**
 * LoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $areaId
     * @return array
     */
    public function findLoansByAreaId($areaId)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 0')
            ->andWhere('l.area = :areaId')
            ->setParameter('areaId', $areaId)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $areaId
     * @param $search
     * @return array
     */
    public function findLoansBySearch($areaId, $search)
    {
        return $this->createQueryBuilder('l')
            ->JOIN('AppBundle:Customer', 'c', 'WITH', 'c.id = l.customer')
            ->where('l.isComplete = 0')
            ->andWhere('l.area = :areaId')
            ->andWhere('c.nic LIKE :search')
            ->setParameter('areaId', $areaId)
            ->setParameter('search', '%' . $search . '%')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $areaId
     * @return array
     */
    public function findCompletedLoansByAreaId($areaId)
    {
        return $this->createQueryBuilder('l')
            ->JOIN('AppBundle:Installment', 'i', 'WITH', 'i.loan = l.id')
            ->where('l.isComplete = 1')
            ->andWhere('l.area = :areaId')
            ->orderBy('i.paymentDate', 'DESC')
            ->setParameter('areaId', $areaId)
            ->getQuery()
            ->getResult();
    }

    /**
     * @param $areaId
     * @param $search
     * @return array
     */
    public function findCompletedLoansBySearch($areaId, $search)
    {
        return $this->createQueryBuilder('l')
            ->JOIN('AppBundle:Customer', 'c', 'WITH', 'c.id = l.customer')
            ->JOIN('AppBundle:Installment', 'i', 'WITH', 'i.loan = l.id')
            ->where('l.isComplete = 1')
            ->andWhere('l.area = :areaId')
            ->andWhere('c.nic LIKE :search')
            ->orderBy('i.paymentDate', 'DESC')
            ->setParameter('areaId', $areaId)
            ->setParameter('search', '%' . $search . '%')
            ->getQuery()
            ->getResult();
    }
}
