<?php

namespace AppBundle\Repository;

/**
 * WitnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitnessRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $witnessNic
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findWitnessByNic($witnessNic)
    {
        return $this->createQueryBuilder('w')
            ->where('w.nic = :witnessNic')
            ->setParameter('witnessNic', $witnessNic)
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
