# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:Admin
                property: name
                # if you're using multiple entity managers
                # manager_name: customer
        in_memory:
            memory: ~

    encoders:
        AppBundle\Entity\Admin:
            algorithm: plaintext
            # cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern:    ^/
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target : login
            provider: our_db_provider
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        # require ROLE_ADMIN for /admin*
      - { path: ^/dashboard , roles: ROLE_ADMIN }