<?php

namespace AppBundle\Entity;

/**
 * InstallmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallmentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $search
     * @return array
     */
    public function findByInstallmentSearch($search)
    {
        return $this->createQueryBuilder('i')
            ->where('i.paymentDate = :search')
            ->setParameter('search', $search)
            ->getQuery()
            ->getResult();
    }

//    /**
//     * @param $loan
//     * @return array
//     */
//    public function findByLoan($loan)
//    {
//        return $this->createQueryBuilder('i')
//            ->where('i.loan = :loan')
//            ->setParameter('loan', $loan)
//            ->orderBy('i.paymentDate', 'DESC')
//            ->getQuery()
//            ->getResult();
//    }

}
