<?php

namespace AppBundle\Entity;

/**
 * LoanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoanRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLoanSearch($search)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 0')
            ->andWhere('l.loanCode LIKE :search')
            ->setParameter('search', '%'.$search.'%')
            ->getQuery()
            ->getResult();
    }

    public function findByCompleteLoanSearch($search)
    {
        return $this->createQueryBuilder('l')
            ->where('l.isComplete = 1')
            ->andWhere('l.loanCode LIKE :search')
            ->setParameter('search', '%'.$search.'%')
            ->getQuery()
            ->getResult();
    }
}
