<?php

namespace AppBundle\Entity;

/**
 * WitnessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WitnessRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByWitnessSearch($search)
    {
        return $this->createQueryBuilder('w')
            ->where('w.name LIKE :search')
            ->orWhere('w.nic LIKE :search')
            ->setParameter('search', '%'.$search.'%')
            ->getQuery()
            ->getResult();
    }
}
